46
pybites/challenges pull request #772
Opened 2020-10-03 07:43 UTC by satyamasthanaa

ATTENTION: before clicking "Create Pull Request" please submit some metadata, thanks!

Difficulty level (1-10): [7]
Estimated time spent (hours): [1]
Completed (yes/no): [yes]

2020-10-03 20:16 UTC, pmayd requested changes
You have pushed two different challenges, 30 and 42, please one PR per challenge

2020-10-03 20:16 UTC, pmayd commented on 30/satyam/ts.py
> +def intro_message():
I like he use of a function for the inro text!

2020-10-03 20:16 UTC, pmayd commented on 30/satyam/ts.py
> +    print('\n' + STEPS_LIST[random.randint(0, len(STEPS_LIST) -1)])
Try out random.choice! https://docs.python.org/3/library/random.html much cleaner

2020-10-06 22:30 UTC, pmayd commented
I am still seeing two different files in two different directories so please decide for one challenge and only commit the files for that particular challenge

2020-10-22 12:28 UTC, bbelderbos commented on 30/satyam/ts.py
> +    print('\n' + STEPS_LIST[random.randint(0, len(STEPS_LIST) -1)])
thanks @pmayd

2020-10-22 12:28 UTC, merged

2020-10-22 12:28 UTC, bbelderbos commented
@satyamasthanaa please open a new PR for challenge #42

2020-10-22 13:57 UTC, satyamasthanaa commented
@bbelderbos Sir, I had already made pull request #42 and it has got merged with the main branch.