Pcc13
pybites/challenges pull request #773
Opened 2020-10-03 18:12 UTC by souhailshiv

ATTENTION: before clicking "Create Pull Request" please submit some meta data, thanks!

Difficulty level (1-10): []
Estimated time spent (hours): []
Completed (yes/no): []
I stretched my coding skills (if yes what did you learn?): []
Other feedback (what can we improve?): []

2020-10-03 18:17 UTC, pmayd requested changes
Please one PR per challenge, you have also commited files for challenge 52

2020-10-03 22:02 UTC, souhailshiv commented
> Please one PR per challenge, you have also commited files for challenge 52

what's do you mean I'm sorry I'm still a beginner in this website

2020-10-04 01:54 UTC, pmayd commented
No problem!  We expect you to open a pull request for each challenge you have solved. However when you look at the files tab you have pushed two files, one in folder 13 and one in 52. So you are handing in two different challenges. One pull request should only contain files in a single folder

2020-10-05 04:08 UTC, pmayd approved these changes
Code is not very pythonic and hard to read, there are a lot of unnecessary type casts and for loops. You create to many dictionaries and don't use python constructs efficiently. Try to spend more time thinking about what you want to code instead of hacking a solution.

2020-10-05 04:08 UTC, pmayd commented on 13/souhailshiv/Highest_Rated_Movie_Directors.py
> +        for item in directors[str(k)]:
Item is not a good name, try to be more specific.

Why do you need a str cast here? Should not b be necessary

2020-10-05 04:08 UTC, pmayd commented on 13/souhailshiv/Highest_Rated_Movie_Directors.py
> +            if int(item[1]) >= MIN_YEAR:
Don't use index access here, movie is a named tuple so you can access its fields with dot notation

2020-10-05 04:08 UTC, pmayd commented on 13/souhailshiv/Highest_Rated_Movie_Directors.py
> +    i = 0
Don't use i explicitly, use pythons enumerate function

2020-10-05 04:08 UTC, pmayd commented on 13/souhailshiv/Highest_Rated_Movie_Directors.py
> +        print(f'\n{colored("%.2d"%i,"magenta")} {k}',
This is hard to read, maybe a helper function for rendering directors

2020-10-05 04:09 UTC, merged